#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

if [ -z "${WM_PROJECT_DIR:-}" ]; then
	echo "OpenFOAM is not loaded. Source its etc/bashrc before running Allrun."
	exit 1
fi

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

runApplication blockMesh
runApplication checkMesh
runApplication $application

#------------------------------------------------------------------------------
